# カメラ設定
camera:
  # VideoCapture のデバイス番号 or パス
  device: 0
  # フレームID (header に付与)
  frame_id: "camera_frame"
  # キャプチャ解像度
  width: 1920
  height: 1080
  # FPS（必要あれば）
  fps: 30

# パイプライン定義のリスト
pipelines:

  # image_detector用のパイプライン：リサイズ→HSV変換
  - name: "resize_hsv_pipeline"
    topic: "/camera/resize_hsv/image_raw"
    operations:
      - type: resize
        width: 640         # 処理しやすいサイズにリサイズ
        height: 480
      - type: color_convert
        encoding: "HSV"    # HSV色空間に変換

  - name: "raw_pipeline"
    topic: "/camera/image_raw"
    operations:
      - type: resize
        width: 640         # 処理しやすいサイズにリサイズ
        height: 480

# ノード全体のパラメータ（例：キューサイズ等）
node_parameters:
  queue_size: 10
  use_camera_info: false
